[pythonsupport]
mail = "pythonsupport@dtu.dk"
homepage = "https://pythonsupport.dtu.dk"
repository = "https://github.com/dtudk/pythonsupport-page"
discord-channel = "https://discord.com/channels/1138793943526539266/1138793944247980124"
discord-invite = "https://discord.gg/h8EVaV9ShP"

online-days = [
   "Monday",
   "Tuesday",
   "Wednesday",
   "Thursday",
   "Friday",
]

python-org-recommended = "https://www.python.org/downloads/release/python-3116/"
python-version.min = "3.8"
python-version.recommended = "3.11"
python-version.max = "3.11"


[semester]
# General, fill in information for all semesters
# If each year does not have anything written, then these
# will be their defaults!
january.name = "3 weeks January"
january.weeks = 3
january.week = ["Closed", "Closed", "Closed"]
january.week-breaks = []

spring.name = "13 weeks Spring"
spring.weeks = 13
spring.week = []
spring.week-breaks = []

june.name = "3 weeks June"
june.weeks = 3
june.week = ["Closed", "Closed", "Closed"]
june.week-breaks = []

autumn.name = "13 weeks Autumn"
autumn.weeks = 13
autumn.week = []
autumn.week-breaks = []


[semester.2024]
january.week-start = 1
spring.week-start = 5
spring.week-breaks = 13
june.week-start = 24
autumn.week-start = 34
autumn.week-breaks = 42

[semester.2023]
january.week-start = 1
spring.week-start = 5
june.week-start = 23
autumn.week-start = 35
autumn.week-breaks = 42


[dtu]
# The course database primary link
course-base = "https://kurser.dtu.dk"

[course.01001]
home = "https://01001.compute.dtu.dk"
[course.01002]
home = "https://01002.compute.dtu.dk"
[course.01003]
home = "https://01003.compute.dtu.dk"
[course.01004]
home = "https://01004.compute.dtu.dk"

[course.02002]
home = "https://02002.compute.dtu.dk/index.html"
[course.02003]
home = "https://02002.compute.dtu.dk/index.html"
